INSERT INTO hrms.cities (id, city_name)
VALUES (3, 'Adana')
     , (4, 'Adıyaman')
     , (5, 'Afyon')
     , (6, 'Ağrı')
     , (7, 'Amasya')
     , (8, 'Ankara')
     , (9, 'Antalya')
     , (10, 'Artvin')
     , (11, 'Aydın')
     , (12, 'Balıkesir')
     , (13, 'Bilecik')
     , (14, 'Bingöl')
     , (15, 'Bitlis')
     , (16, 'Bolu')
     , (17, 'Burdur')
     , (18, 'Bursa')
     , (19, 'Çanakkale')
     , (20, 'Çankırı')
     , (21, 'Çorum')
     , (22, 'Denizli')
     , (23, 'Diyarbakır')
     , (24, 'Edirne')
     , (25, 'Elazığ')
     , (26, 'Erzincan')
     , (27, 'Erzurum ')
     , (28, 'Eskişehir')
     , (29, 'Gaziantep')
     , (30, 'Giresun')
     , (31, 'Gümüşhane')
     , (32, 'Hakkari')
     , (33, 'Hatay')
     , (34, 'Isparta')
     , (35, 'Mersin')
     , (36, 'İstanbul')
     , (37, 'İzmir')
     , (38, 'Kars')
     , (39, 'Kastamonu')
     , (40, 'Kayseri')
     , (41, 'Kırklareli')
     , (42, 'Kırşehir')
     , (43, 'Kocaeli')
     , (44, 'Konya')
     , (45, 'Kütahya ')
     , (46, 'Malatya')
     , (47, 'Manisa')
     , (48, 'Kahramanmaraş')
     , (49, 'Mardin')
     , (50, 'Muğla')
     , (51, 'Muş')
     , (52, 'Nevşehir')
     , (53, 'Niğde')
     , (54, 'Ordu')
     , (55, 'Rize')
     , (56, 'Sakarya')
     , (57, 'Samsun')
     , (58, 'Siirt')
     , (59, 'Sinop')
     , (60, 'Sivas')
     , (61, 'Tekirdağ')
     , (62, 'Tokat')
     , (63, 'Trabzon  ')
     , (64, 'Tunceli')
     , (65, 'Şanlıurfa')
     , (66, 'Uşak')
     , (67, 'Van')
     , (68, 'Yozgat')
     , (69, 'Zonguldak')
     , (70, 'Aksaray')
     , (71, 'Bayburt ')
     , (72, 'Karaman')
     , (73, 'Kırıkkale')
     , (74, 'Batman')
     , (75, 'Şırnak')
     , (76, 'Bartın')
     , (77, 'Ardahan')
     , (78, 'Iğdır')
     , (79, 'Yalova')
     , (80, 'Karabük ')
     , (81, 'Kilis')
     , (82, 'Osmaniye ')
     , (83, 'Düzce')
;
